batch_momentum: 0.2
batch_size: 80
gps_lat: GPS_LAT
gps_lon: GPS_LONG
learning_rate: 0.0005751086412393303
loss: l2
maxf: 64
minf: 32
nclasses: 0
nlayers: 1
non_linearity: relu
num_workers: 8
sep: ','
src: multi_dem
src_vars:
- Band_1
- Band_2
- Band_3
- Band_4
- Band_5
- Band_6
- Band_7
- Band_8
- Band_9
- Band_10
- Band_11
- Band_12
- Band_13
- Band_14
- Band_15
- Band_16
- Band_17
- Band_18
- Band_19
- Band_20
- Band_21
- CATCH_SLOP
- TWI
- SLOPE_LENG
- CN_BASE
- VDCN
- VALLEY_DEP
- SLOPE
- DEM
test_csv: /home/flavio/datasets/LucasLibrary/peracchi/lucas_dataset_test.csv
tgt_vars:
- coarse
- clay
- silt
- sand
- pH.in.CaCl
- pH.in.H2O
- OC
- CaCO3
- N
- P
- K
- CEC
train_csv: /home/flavio/datasets/LucasLibrary/peracchi/lucas_dataset_train.csv
use_batchnorm: true
val: r2
val_csv: /home/flavio/datasets/LucasLibrary/peracchi/lucas_dataset_val.csv
weight_decay: 0.0015482062686671416
